/**
 * The disclosure policy.
 *
 * This is the security boundary of the whole application. Every number that ever reaches the
 * agent, the DOM, or a canvas passes through here first.
 *
 * The invariant it exists to enforce:
 *
 *   No individual-level value is released through the registered tool interface or rendered
 *   to the DOM, under the stated disclosure policy. The page's own memory is out of scope.
 *   This is not a cryptographic boundary.
 *
 * Read `docs/threat-model.md` before relaxing anything here. Several rules that look
 * conservative are load-bearing against specific published attacks, noted inline.
 */

/* ------------------------------------------------------------------ *
 * Constants                                                          *
 * ------------------------------------------------------------------ */

/** Counts at or above this are the only ones eligible for exact disclosure. */
export const COUNT_EXACT_FLOOR = 50;

/** Below this, a cohort does not exist as far as the agent is concerned. */
export const K_COUNT_FLOOR = 5;

/**
 * Any *numeric* statistic requires at least this many records.
 *
 * This is deliberately far above K_COUNT_FLOOR, and it is the single most important number
 * in the file. At small n, order statistics ARE individual values: with the standard
 * linear-interpolation quantile definition, index = (n-1)*q, so at n=5 the median is exactly
 * the third person's salary and p25/p75 are the second and fourth. A k=5 floor on a statistic
 * whose influence support is 1 is not a floor at all.
 */
export const N_NUMERIC_FLOOR = 20;

/** Currency is rounded to this. Coarse enough that a recovered value is a band, not a salary. */
export const CURRENCY_QUANTUM = 500;

/** Decimal places for unitless ratios. */
export const RATIO_DP = 2;

/** Percentage-point quantum for the headline gap figure. */
export const PP_QUANTUM = 0.5;

/**
 * Maximum number of dimensions in a single group-by.
 *
 * Bounding the tool vocabulary bounds *syntax*, not *expressiveness*: the lattice generated by
 * a handful of enums still spans a very large predicate space, which is what marginal
 * reconstruction attacks consume. Capping depth is what actually limits the lattice.
 */
export const MAX_GROUP_BY_DEPTH = 2;

/**
 * Session budget, denominated in *released cells* rather than tool calls.
 *
 * Counting calls is the wrong unit. One grouped query returns a whole table, so a 60-call
 * budget can release thousands of cells. Cells are what an adversary actually spends.
 */
export const BUDGET_CELLS = 400;

/* ------------------------------------------------------------------ *
 * Statistics                                                         *
 * ------------------------------------------------------------------ */

/**
 * The complete set of permitted statistics.
 *
 * Deliberately absent, each for a specific reason:
 *
 *   min / max / top-N  an extremum IS an individual's value.
 *   stddev             a zero-variance cell discloses every member exactly, and mean+stddev
 *                      +count bounds every observation via Samuelson's inequality
 *                      (|x - mean| <= s*sqrt(n-1)). Combined with quartiles it yields
 *                      closed-form recovery of min and max. This is the homogeneity attack
 *                      that motivated l-diversity.
 *   mode               the modal value is an observed value.
 *   sum                sum plus a count from any overlapping query is a mean; and sums
 *                      difference cleanly across nested cohorts.
 *
 *   median / p25 / p75 REMOVED after a security review demonstrated recovery of 53 exact
 *                      salaries. An order statistic has an INFLUENCE SUPPORT of one or two
 *                      records regardless of cohort size: with index = (n-1)*q, the value is a
 *                      bare `sorted[i]` whenever that index is an integer — every odd n for the
 *                      median, every n congruent to 1 mod 4 for the quartiles. So the median of
 *                      a 363-person cohort is exactly one person's salary.
 *
 *                      An earlier version of this file diagnosed precisely that defect and then
 *                      "fixed" it by raising the cohort floor to 20, which does nothing: the
 *                      support of a median is 1 at every odd n, not merely at small n. Raising a
 *                      cohort floor cannot repair a statistic whose support does not grow with
 *                      the cohort. The statistic had to go.
 *
 *                      `mean` is retained because its support is n: every record contributes
 *                      1/n, so no single record determines the output.
 */
export const ALLOWED_STATS = ['count', 'mean'] as const;
export type Stat = (typeof ALLOWED_STATS)[number];

/** Statistics that read a metric's values, and therefore require N_NUMERIC_FLOOR. */
export const NUMERIC_STATS: readonly Stat[] = ['mean'];

/**
 * Statistics that were once permitted and are now refused by name.
 *
 * Kept explicit so the refusal is informative rather than a generic "unknown statistic", and so
 * the reason is discoverable by anyone reading the code or the exported report.
 */
export const WITHDRAWN_STATS = ['median', 'p25', 'p75', 'quartile', 'percentile'] as const;

/**
 * Minimum number of distinct values a cohort must contain before any statistic over it may be
 * released.
 *
 * A cohort whose values are all identical is a zero-variance cohort, and ANY measure of central
 * tendency over it discloses every member exactly. This is the homogeneity attack that motivated
 * l-diversity, and it does not require `stddev` to exploit: on a non-negative metric, a mean of
 * zero proves every member is zero. In this dataset that single fact would have disclosed the
 * exact equity value of 1,305 people in one call.
 *
 * Excluding dispersion statistics is not sufficient protection against dispersion being zero.
 */
export const MIN_DISTINCT_VALUES = 2;

/**
 * Minimum number of strata that must contribute to a stratified figure.
 *
 * A stratified result computed from a single stratum is not stratified — it is that stratum's
 * ratio, released at a grouping depth the policy otherwise forbids. Requiring several strata is
 * what makes the released number genuinely an aggregate of aggregates.
 */
export const MIN_STRATA = 4;

export function isAllowedStat(s: string): s is Stat {
  return (ALLOWED_STATS as readonly string[]).includes(s);
}

export function isNumericStat(s: Stat): boolean {
  return NUMERIC_STATS.includes(s);
}

/* ------------------------------------------------------------------ *
 * Refusals                                                           *
 * ------------------------------------------------------------------ */

/**
 * Refusal codes.
 *
 * Refusals are returned as VALUES, never thrown. The WebMCP spec discards a rejected
 * promise's reason: the caller receives a generic UnknownError and the message is lost. An
 * agent that cannot read why it was refused cannot adapt, and the refusal is the centre of
 * this product.
 */
export type RefusalCode =
  | 'INSUFFICIENT_SUPPORT'
  | 'STAT_NOT_PERMITTED'
  | 'STAT_WITHDRAWN'
  | 'GROUP_BY_TOO_DEEP'
  | 'UNKNOWN_DIMENSION'
  | 'UNKNOWN_METRIC'
  | 'BUDGET_EXHAUSTED'
  | 'BUDGET_INSUFFICIENT'
  | 'NO_DATASET';

/**
 * Refusal text is a pure function of the CODE, never of the data.
 *
 * A message like "insufficient support: n=4" publishes the very count the banding rule
 * exists to hide, and turns every refusal into a one-bit oracle that can be walked to
 * locate the smallest cohorts — exactly where the remaining attacks are strongest.
 */
const REFUSAL_TEXT: Record<RefusalCode, { reason: string; recovery: string }> = {
  INSUFFICIENT_SUPPORT: {
    reason: 'Policy: this cohort has too few people to report on.',
    recovery: 'Group by fewer dimensions, or choose a broader cohort.'
  },
  STAT_NOT_PERMITTED: {
    reason: `Policy: permitted statistics are ${ALLOWED_STATS.join(', ')}.`,
    recovery: 'Extremes and dispersion are not available at any cohort size. Use mean.'
  },
  STAT_WITHDRAWN: {
    reason:
      'Policy: order statistics are not available at any cohort size, because a median or '
      + 'quartile is one specific person\'s value however large the cohort.',
    recovery: 'Use mean, whose value depends on every member of the cohort.'
  },
  GROUP_BY_TOO_DEEP: {
    reason: `Policy: at most ${MAX_GROUP_BY_DEPTH} dimensions may be combined.`,
    recovery: 'Drop a dimension and run the analysis in two passes.'
  },
  UNKNOWN_DIMENSION: {
    reason: 'Policy: unrecognised dimension.',
    recovery: 'Call describe_dataset for the permitted dimensions.'
  },
  UNKNOWN_METRIC: {
    reason: 'Policy: unrecognised metric.',
    recovery: 'Call describe_dataset for the permitted metrics.'
  },
  BUDGET_EXHAUSTED: {
    reason: 'Policy: the disclosure budget for this session is spent.',
    recovery: 'The person at the keyboard can extend the budget in the page.'
  },
  BUDGET_INSUFFICIENT: {
    reason: 'Policy: this query would disclose more than the remaining budget allows.',
    recovery: 'Group by fewer dimensions, or ask the person at the keyboard to extend the budget.'
  },
  NO_DATASET: {
    reason: 'No dataset is loaded.',
    recovery: 'Call load_sample_dataset first.'
  }
};

export interface Refusal {
  status: 'refused';
  code: RefusalCode;
  reason: string;
  recovery: string;
}

export function refuse(code: RefusalCode): Refusal {
  const t = REFUSAL_TEXT[code];
  return { status: 'refused', code, reason: t.reason, recovery: t.recovery };
}

/* ------------------------------------------------------------------ *
 * Quantization                                                       *
 * ------------------------------------------------------------------ */

export function quantizeCurrency(v: number): number {
  return Math.round(v / CURRENCY_QUANTUM) * CURRENCY_QUANTUM;
}

export function quantizeRatio(v: number): number {
  const f = 10 ** RATIO_DP;
  return Math.round(v * f) / f;
}

export function quantizePP(v: number): number {
  return Math.round(v / PP_QUANTUM) * PP_QUANTUM;
}

export type Unit = 'currency' | 'ratio' | 'pp' | 'count';

export function quantize(v: number, unit: Unit): number {
  switch (unit) {
    case 'currency': return quantizeCurrency(v);
    case 'ratio': return quantizeRatio(v);
    case 'pp': return quantizePP(v);
    case 'count': return Math.round(v);
  }
}

/* ------------------------------------------------------------------ *
 * Count banding                                                      *
 * ------------------------------------------------------------------ */

export type CountBand = '<5' | '5-9' | '10-24' | '25-49' | number;

/**
 * Counts are banded below COUNT_EXACT_FLOOR.
 *
 * Exact small counts are the missing ingredient for several attacks: they identify which
 * cohorts sit at the floor, and regression degrees-of-freedom style leaks become useful only
 * once n is known precisely. Banding is cheap and removes that ingredient.
 */
export function bandCount(n: number): CountBand {
  if (n < K_COUNT_FLOOR) return '<5';
  if (n < 10) return '5-9';
  if (n < 25) return '10-24';
  if (n < COUNT_EXACT_FLOOR) return '25-49';
  return n;
}

/* ------------------------------------------------------------------ *
 * Gates                                                              *
 * ------------------------------------------------------------------ */

/** True when a cohort of size n may have the given statistic reported. */
export function statPermittedAt(stat: Stat, n: number): boolean {
  return isNumericStat(stat) ? n >= N_NUMERIC_FLOOR : n >= K_COUNT_FLOOR;
}

/**
 * The post-computation gate.
 *
 * Every other control in this file inspects the *request*: which statistic, how many dimensions,
 * how large the cohort. None of them inspect what actually came out. That gap was the root cause
 * of both critical findings in review — a statistic can be allow-listed and a cohort can clear
 * every floor while the released number is still one person's value.
 *
 * This is the last check before a number leaves the kernel. It takes the realised cohort values
 * and answers a single question: could this output be attributed to an individual?
 */
export function outputPermitted(values: readonly number[]): { ok: true } | { ok: false; code: RefusalCode } {
  if (values.length < N_NUMERIC_FLOOR) {
    return { ok: false, code: 'INSUFFICIENT_SUPPORT' };
  }

  // Zero-variance cohort. Any measure of central tendency over it discloses every member.
  // Checked on realised values rather than inferred from the statistic's name, because a mean
  // of zero on a non-negative metric is a homogeneity disclosure even though `mean` is safe in
  // general.
  const distinct = new Set(values);
  if (distinct.size < MIN_DISTINCT_VALUES) {
    return { ok: false, code: 'INSUFFICIENT_SUPPORT' };
  }

  return { ok: true };
}
